import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import Provider from "@/context/Provider";

const outfitLight = localFont({
  src: "./fonts/OutfitLight.woff",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider
        session={{
          user: { id: "", name: null, email: null, image: null },
          expires: "",
        }}
      >
        <body
          className={`${outfitLight.className} bg-primary-900 text-primary-100`}
        >
          <div className="lg:flex">
            <Header />
            {children}
          </div>
        </body>
      </Provider>
    </html>
  );
}
